import random


#Config for your rounds

no_of_rounds = 0
upto_atomic_number = 0


chemical_elements = [
    {"symbol": "H", "name": "Hydrogen", "atomic_number": 1, "mass": 1.008},
    {"symbol": "He", "name": "Helium", "atomic_number": 2, "mass": 4.0026},
    {"symbol": "Li", "name": "Lithium", "atomic_number": 3, "mass": 6.94},
    {"symbol": "Be", "name": "Beryllium", "atomic_number": 4, "mass": 9.0122},
    {"symbol": "B", "name": "Boron", "atomic_number": 5, "mass": 10.81},
    {"symbol": "C", "name": "Carbon", "atomic_number": 6, "mass": 12.011},
    {"symbol": "N", "name": "Nitrogen", "atomic_number": 7, "mass": 14.007},
    {"symbol": "O", "name": "Oxygen", "atomic_number": 8, "mass": 15.999},
    {"symbol": "F", "name": "Fluorine", "atomic_number": 9, "mass": 18.998},
    {"symbol": "Ne", "name": "Neon", "atomic_number": 10, "mass": 20.18},
    {"symbol": "Na", "name": "Sodium", "atomic_number": 11, "mass": 22.99},
    {"symbol": "Mg", "name": "Magnesium", "atomic_number": 12, "mass": 24.305},
    {"symbol": "Al", "name": "Aluminum", "atomic_number": 13, "mass": 26.982},
    {"symbol": "Si", "name": "Silicon", "atomic_number": 14, "mass": 28.085},
    {"symbol": "P", "name": "Phosphorus", "atomic_number": 15, "mass": 30.974},
    {"symbol": "S", "name": "Sulfur", "atomic_number": 16, "mass": 32.06},
    {"symbol": "Cl", "name": "Chlorine", "atomic_number": 17, "mass": 35.45},
    {"symbol": "Ar", "name": "Argon", "atomic_number": 18, "mass": 39.948},
    {"symbol": "K", "name": "Potassium", "atomic_number": 19, "mass": 39.098},
    {"symbol": "Ca", "name": "Calcium", "atomic_number": 20, "mass": 40.078},
    {"symbol": "Sc", "name": "Scandium", "atomic_number": 21, "mass": 44.956},
    {"symbol": "Ti", "name": "Titanium", "atomic_number": 22, "mass": 47.867},
    {"symbol": "V", "name": "Vanadium", "atomic_number": 23, "mass": 50.942},
    {"symbol": "Cr", "name": "Chromium", "atomic_number": 24, "mass": 51.996},
    {"symbol": "Mn", "name": "Manganese", "atomic_number": 25, "mass": 54.938},
    {"symbol": "Fe", "name": "Iron", "atomic_number": 26, "mass": 55.845},
    {"symbol": "Co", "name": "Cobalt", "atomic_number": 27, "mass": 58.933},
    {"symbol": "Ni", "name": "Nickel", "atomic_number": 28, "mass": 58.693},
    {"symbol": "Cu", "name": "Copper", "atomic_number": 29, "mass": 63.546},
    {"symbol": "Zn", "name": "Zinc", "atomic_number": 30, "mass": 65.38},
    {"symbol": "Ga", "name": "Gallium", "atomic_number": 31, "mass": 69.723},
    {"symbol": "Ge", "name": "Germanium", "atomic_number": 32, "mass": 72.63},
    {"symbol": "As", "name": "Arsenic", "atomic_number": 33, "mass": 74.922},
    {"symbol": "Se", "name": "Selenium", "atomic_number": 34, "mass": 78.971},
    {"symbol": "Br", "name": "Bromine", "atomic_number": 35, "mass": 79.904},
    {"symbol": "Kr", "name": "Krypton", "atomic_number": 36, "mass": 83.798},
    {"symbol": "Rb", "name": "Rubidium", "atomic_number": 37, "mass": 85.468},
    {"symbol": "Sr", "name": "Strontium", "atomic_number": 38, "mass": 87.62},
    {"symbol": "Y", "name": "Yttrium", "atomic_number": 39, "mass": 88.906},
    {"symbol": "Zr", "name": "Zirconium", "atomic_number": 40, "mass": 91.224},
    {"symbol": "Nb", "name": "Niobium", "atomic_number": 41, "mass": 92.906},
    {"symbol": "Mo", "name": "Molybdenum", "atomic_number": 42, "mass": 95.95},
    {"symbol": "Tc", "name": "Technetium", "atomic_number": 43, "mass": 98},
    {"symbol": "Ru", "name": "Ruthenium", "atomic_number": 44, "mass": 101.07},
    {"symbol": "Rh", "name": "Rhodium", "atomic_number": 45, "mass": 102.91},
    {"symbol": "Pd", "name": "Palladium", "atomic_number": 46, "mass": 106.42},
    {"symbol": "Ag", "name": "Silver", "atomic_number": 47, "mass": 107.87},
    {"symbol": "Cd", "name": "Cadmium", "atomic_number": 48, "mass": 112.41},
    {"symbol": "In", "name": "Indium", "atomic_number": 49, "mass": 114.82},
    {"symbol": "Sn", "name": "Tin", "atomic_number": 50, "mass": 118.71},
    {"symbol": "Sb", "name": "Antimony", "atomic_number": 51, "mass": 121.76},
    {"symbol": "Te", "name": "Tellurium", "atomic_number": 52, "mass": 127.6},
    {"symbol": "I", "name": "Iodine", "atomic_number": 53, "mass": 126.9},
    {"symbol": "Xe", "name": "Xenon", "atomic_number": 54, "mass": 131.29},
    {"symbol": "Cs", "name": "Cesium", "atomic_number": 55, "mass": 132.91},
    {"symbol": "Ba", "name": "Barium", "atomic_number": 56, "mass": 137.33},
    {"symbol": "La", "name": "Lanthanum", "atomic_number": 57, "mass": 138.91},
    {"symbol": "Ce", "name": "Cerium", "atomic_number": 58, "mass": 140.12},
    {"symbol": "Pr", "name": "Praseodymium", "atomic_number": 59, "mass": 140.91},
    {"symbol": "Nd", "name": "Neodymium", "atomic_number": 60, "mass": 144.24},
    {"symbol": "Pm", "name": "Promethium", "atomic_number": 61, "mass": 145},
    {"symbol": "Sm", "name": "Samarium", "atomic_number": 62, "mass": 150.36},
    {"symbol": "Eu", "name": "Europium", "atomic_number": 63, "mass": 151.96},
    {"symbol": "Gd", "name": "Gadolinium", "atomic_number": 64, "mass": 157.25},
    {"symbol": "Tb", "name": "Terbium", "atomic_number": 65, "mass": 158.93},
    {"symbol": "Dy", "name": "Dysprosium", "atomic_number": 66, "mass": 162.5},
    {"symbol": "Ho", "name": "Holmium", "atomic_number": 67, "mass": 164.93},
    {"symbol": "Er", "name": "Erbium", "atomic_number": 68, "mass": 167.26},
    {"symbol": "Tm", "name": "Thulium", "atomic_number": 69, "mass": 168.93},
    {"symbol": "Yb", "name": "Ytterbium", "atomic_number": 70, "mass": 173.05},
    {"symbol": "Lu", "name": "Lutetium", "atomic_number": 71, "mass": 174.97},
    {"symbol": "Hf", "name": "Hafnium", "atomic_number": 72, "mass": 178.49},
    {"symbol": "Ta", "name": "Tantalum", "atomic_number": 73, "mass": 180.95},
    {"symbol": "W", "name": "Tungsten", "atomic_number": 74, "mass": 183.84},
    {"symbol": "Re", "name": "Rhenium", "atomic_number": 75, "mass": 186.21},
    {"symbol": "Os", "name": "Osmium", "atomic_number": 76, "mass": 190.23},
    {"symbol": "Ir", "name": "Iridium", "atomic_number": 77, "mass": 192.22},
    {"symbol": "Pt", "name": "Platinum", "atomic_number": 78, "mass": 195.08},
    {"symbol": "Au", "name": "Gold", "atomic_number": 79, "mass": 196.97},
    {"symbol": "Hg", "name": "Mercury", "atomic_number": 80, "mass": 200.59},
    {"symbol": "Tl", "name": "Thallium", "atomic_number": 81, "mass": 204.38},
    {"symbol": "Pb", "name": "Lead", "atomic_number": 82, "mass": 207.2},
    {"symbol": "Bi", "name": "Bismuth", "atomic_number": 83, "mass": 208.98},
    {"symbol": "Po", "name": "Polonium", "atomic_number": 84, "mass": 209},
    {"symbol": "At", "name": "Astatine", "atomic_number": 85, "mass": 210},
    {"symbol": "Rn", "name": "Radon", "atomic_number": 86, "mass": 222},
    {"symbol": "Fr", "name": "Francium", "atomic_number": 87, "mass": 223},
    {"symbol": "Ra", "name": "Radium", "atomic_number": 88, "mass": 226},
    {"symbol": "Ac", "name": "Actinium", "atomic_number": 89, "mass": 227},
    {"symbol": "Th", "name": "Thorium", "atomic_number": 90, "mass": 232.04},
    {"symbol": "Pa", "name": "Protactinium", "atomic_number": 91, "mass": 231.04},
    {"symbol": "U", "name": "Uranium", "atomic_number": 92, "mass": 238.03},
    {"symbol": "Np", "name": "Neptunium", "atomic_number": 93, "mass": 237},
    {"symbol": "Pu", "name": "Plutonium", "atomic_number": 94, "mass": 244},
    {"symbol": "Am", "name": "Americium", "atomic_number": 95, "mass": 243},
    {"symbol": "Cm", "name": "Curium", "atomic_number": 96, "mass": 247},
    {"symbol": "Bk", "name": "Berkelium", "atomic_number": 97, "mass": 247},
    {"symbol": "Cf", "name": "Californium", "atomic_number": 98, "mass": 251},
    {"symbol": "Es", "name": "Einsteinium", "atomic_number": 99, "mass": 252},
    {"symbol": "Fm", "name": "Fermium", "atomic_number": 100, "mass": 257},
    {"symbol": "Md", "name": "Mendelevium", "atomic_number": 101, "mass": 258},
    {"symbol": "No", "name": "Nobelium", "atomic_number": 102, "mass": 259},
    {"symbol": "Lr", "name": "Lawrencium", "atomic_number": 103, "mass": 266},
    {"symbol": "Rf", "name": "Rutherfordium", "atomic_number": 104, "mass": 267},
    {"symbol": "Db", "name": "Dubnium", "atomic_number": 105, "mass": 270},
    {"symbol": "Sg", "name": "Seaborgium", "atomic_number": 106, "mass": 271},
    {"symbol": "Bh", "name": "Bohrium", "atomic_number": 107, "mass": 270},
    {"symbol": "Hs", "name": "Hassium", "atomic_number": 108, "mass": 277},
    {"symbol": "Mt", "name": "Meitnerium", "atomic_number": 109, "mass": 276},
    {"symbol": "Ds", "name": "Darmstadtium", "atomic_number": 110, "mass": 281},
    {"symbol": "Rg", "name": "Roentgenium", "atomic_number": 111, "mass": 280},
    {"symbol": "Cn", "name": "Copernicium", "atomic_number": 112, "mass": 285},
    {"symbol": "Nh", "name": "Nihonium", "atomic_number": 113, "mass": 284},
    {"symbol": "Fl", "name": "Flerovium", "atomic_number": 114, "mass": 289},
    {"symbol": "Mc", "name": "Moscovium", "atomic_number": 115, "mass": 288},
    {"symbol": "Lv", "name": "Livermorium", "atomic_number": 116, "mass": 293},
    {"symbol": "Ts", "name": "Tennessine", "atomic_number": 117, "mass": 294},
    {"symbol": "Og", "name": "Oganesson", "atomic_number": 118, "mass": 294},
]


print(f'\n\nThis Round will be of {no_of_rounds} questions.\n\n')
win = 0

for i in range(1,no_of_rounds):
    teplememt = chemical_elements[random.randrange(0,upto_atomic_number)]
    i = int(input(f'What is the atomic no. of {teplememt["name"]} : '))
    if i == teplememt["atomic_number"]:
        print('correct!!')
        win += 1
    else:
        print('incorrect')
print(f"Your score = {win}/{no_of_rounds}.")
input()